version: "3.4"

services:
  web:
    image: ambientum/php:7.4-nginx
    container_name: simple-bank
    volumes:
      - .:/var/www/app:delegated
    ports:
      - 8753:8080
    depends_on:
      - postgres
    environment:
      - PHP_MEMORY_LIMIT=-1
      - COMPOSER_MEMORY_LIMIT=-1
  postgres:
    image: postgres:12-alpine
    container_name: simple-bank-postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=simple_bank
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - simple-bank-data:/var/lib/postgresql/data:delegated
volumes:
  simple-bank-data:
    driver: local
